SELECT C_COUNT, COUNT(*) AS TOTAL
FROM (
SELECT C_CUSTKEY, COUNT(O_ORDERKEY) AS CNT
FROM CUSTOMER LEFT OUTER JOIN ORDERS ON C_CUSTKEY = O_CUSTKEY
WHERE O_COMMENT NOT LIKE '%%unusual%%packages%%'
GROUP BY C_CUSTKEY 
) AS TMP_VIEW
GROUP BY CNT AS C_COUNT
ORDER BY TOTAL DESC, C_COUNT DESC
